import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const myFont = localFont({ src: "../public/fonts/SFProDisplay-Regular.woff2" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        <main className="grid grid-cols-1 max-w-7xl mx-auto items-center h-screen">
          {children}
        </main>
        {modal}
      </body>
    </html>
  );
}
